---
- name: Ping ec2 instances
  hosts: all
  gather_facts: True

  tasks:
  - name: Debug gather facts
    ansible.builtin.debug:
      var: ansible_facts["distribution"]
  
  - name: testing ping command
    ansible.builtin.ping: